### ISSUE TITLE
Provide better error information

### ISSUE THREAD

**Issue by massenz** [Joxit/docker-registry-ui#25]
I am using this to connect to a plain vanilla private registry running on `localhost:5000` and, while I'm sure the registry works just fine (a `GET localhost:5000/v2/_catalog` returns all correct values (there is no authentication, no https) and another UI works just fine, this just fails with a:

    An Error occurred

and no information about what could possibly have gone wrong.

I start the UI with:
```
$ docker run -d -p 80:80 -e URL=http://127.0.0.1:5000 -e DELETE_IMAGES=true joxit/docker-registry-ui:static
81445a6f88c7dcdcd82e034143179707b63544f398653fbc911a69a7f33a0f00
```
This is a simple example to verify the registry API is reachable:
```
$ curl -fs http://localhost:5000/v2/_catalog | python -m json.tool
{
    "repositories": [
        "8caa8/entry",
        "server/base"
    ]
}
```

**Comment by Joxit** [comment]
Hi,
What is your docker registry configuration ?
It may be a CORS issue, see [this](https://joxit.github.io/docker-registry-ui/#using-cors) for a good docker registry configuration. You must add an Access-Control-Allow-Origin header in server response to indicating which origin sites are allowed.

**Comment by massenz** [comment]
This is just a dev instance, so I'm running the registry straight from [these Instructions](https://docs.docker.com/registry/deploying/):

    $ docker run -d -p 5000:5000 --restart=always --name registry-srv registry:2

Also, as mentioned above, a straight `curl` gets the list of images and another Registry Web UI I'm now using (`hyper/docker-registry-web`) works just fine.

> You must add an Access-Control-Allow-Origin header in server response

While I won't argue with your design choices, I would contend that this should be rather unnecessary in a "plain vanilla" dev deployment where one just wishes to see what's possible; especially considering that a plain 'curl' "just works."

And, by the way, thanks for confirming that a better error message would be helpful to everyone 😆 

It's really too bad about this: while I have found something "that works," this one seemed to have the promise of a better, more pleasant UI - I guess we'll never know...

**Comment by Joxit** [comment]
[CORS (or Cross-origin Resource Sharing)](https://fr.wikipedia.org/wiki/Cross-origin_resource_sharing) is a browser security and allow by default only [Same Origin](https://en.wikipedia.org/wiki/Same-origin_policy) requests (same URI scheme, host name, and port number). This policy prevents a malicious script on one page from obtaining access to sensitive data on another web page.

If you have the UI on http://localhost/ and registry on http://localhost:5000, without the CORS header your browser will drop the request without notification. That is why `joxit/docker-registry-ui` can't show your private registry.

For the error message, CORS related errors raises `error` event on [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest), and as defined in [specs](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequestEventTarget/onerror#Browser_compatibility), this don't give custom message. That why we can't have better error messages... :disappointed:

`joxit/docker-registry-ui` is a standalone User Interface and `hyper/docker-registry-web` is a Java webapp with a middleware for the docker registry, that why there are no CORS issue.

If you don't want to add a configuration file, you can also run your docker registry with the extra option `-e REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin="*"`.

Anyway, I will add a new proxy config with Nginx, this should fix your issue :wink:

**Comment by Joxit** [comment]
Fixed with bf3e3c9

**Comment by nvmnghia** [comment]
I still can't get it to work :(

Here's my `config.yml` file:

```yml
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
    Access-Control-Allow-Origin: ['*']
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
#    Access-Control-Allow-Headers: ['Authorization']
#    Access-Control-Max-Age: [1728000]
#    Access-Control-Allow-Credentials: [true]
#    Access-Control-Expose-Headers: ['Docker-Content-Digest']

health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
```

Both the UI and the registry is running inside docker, using these command:

```bash
docker run -d -p 5000:5000 --name registry registry:latest
docker run -d -p 8080:80 -e URL=localhost:5000 --name docker-registry-ui joxit/docker-registry-ui:static
```

**Comment by Joxit** [comment]
The issue is in your `URL` environment, you should set URL to `http://localhost:5000` and not `localhost:5000`. the `http://` part is required.

**Comment by Joxit** [comment]
You are welcome :heart:

**Comment by xmontero** [comment]
By your words I understand that the communication to the registry is done by the browser and then rendered in javascript, not requests to your application and then the application requesting the registry, I guess.

Could this be solved browser-side? I mean... I don't want to tell my registry rare things... Even I don't want that to be my default behaviour. Could I tell to my locally-installed Firefox "hey, you browser are allowed to run requests to 192.168.2.55:5000 (where I have the registry) even if the page loaded from 192.168.2.55:9998 (where I export your project)?

At the end, it's not a registry problem, it's a browsing problem... Could we enable a "per casis" browser CORS exception?

**Comment by Joxit** [comment]
IMO, this is a registry miss-configuration and not a browser issue. CORS are used to protect us when browsing. 

The second solution is to use the docker image `joxit/docker-registry-ui:static` with `REGISTRY_URL`, this configuration should avoid CORS errors ([example with docker compose](https://github.com/Joxit/docker-registry-ui/blob/master/examples/ui-as-proxy/simple.yml)).

You can remove CORS restriction, but do this at your own risks !
Steps for Firefox: 
```
about:config -> security.fileuri.strict_origin_policy -> false
```
sources: [stackoverflow](https://stackoverflow.com/questions/17088609/disable-firefox-same-origin-policy), [symantec](https://help.symantec.com/cs/DCS1.0/DCS1_0/v107680513_v99309261/Enabling-CORS?locale=EN_US)

Read more about CORS: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by xmontero** [comment]
Sure. I did not mean "completely disable CORS in general". I agree this is not desirable.

I meant if we could tell Firefox "This X address is allowed to go to this Y address. But, hey browser, continue restricting the rest".

The same way when we find an outdated SSL/TSL certificate when browing an `https://` page we do not need to tell the browser "hey, ignore the expiration date of all certificates" but we instruct to ignore just "that" specific certificate and continue secured in the rest of the pages.

If we could "disable CORS" selectively in the browser that would solve the problem.

**Comment by xmontero** [comment]
# Works

Indeed, found it.

a) It is possible (at least with firefox)

b) IMHO I think it's cleaner doing it from the browser, as the registry itself "should not know" what clients are there. The same way no sysop would tune a MySQL server "just because someone willing to connect does some weird things" I don't think the docker registry should know about anything hot it is accessed. The server is the server; and the registry itself does not care what happens in the client side. It serves an API and that's all.

# Selectively allow CORS on firefox

So... going to the stuff...

In Firefox, there's this add-on: "CORS Everywhere" https://addons.mozilla.org/es/firefox/addon/cors-everywhere/?src=search that allows us SELECTIVELY to trick the CORS only for that setup.

Once installed, you can enable/disable CORS tricking:

![imagen](https://user-images.githubusercontent.com/5641621/80582579-41204d80-8a0f-11ea-986f-2186bc8399c2.png)

This icon means "deactivated, do nothing", all browsing is safe.

![imagen](https://user-images.githubusercontent.com/5641621/80582758-8e9cba80-8a0f-11ea-9e77-f57660a4cfc3.png)

This other icon means "browse safely for all the internet BUT for those white-listed sites, allow CORS". The trick is done by altering the response sent from the server so it effectively if it like if we set it server-side BUT without having to alter the server, which was the desired behaviour.

In the "CORS Weverywhere" setup you must whitelist a regex matching the REGISTRY SERVER address, which is the one that will be tricked.

![imagen](https://user-images.githubusercontent.com/5641621/80583164-28646780-8a10-11ea-9c0e-82c6ede465c0.png)

Set the domain for the registry or the IP address in the configuration. I explicitly avoided the "s" in the http and explicitly allowed any port, for my flexibility, but the regex could be more fine-tuned.

I guess there must be similar addons for chrome and other browsers.

# Test

I loaded the Joxit/docker-registry-ui and saw it failing.
Then I tuned the extension configuration.
I Reloaded the Joxit/docker-registry-ui with CTRL-F5 and boom worked.
Just to test, I set an extra character in the configuration to force a mismatch. Saved. Reloaded. Boom failed (as expected).
Re-set the correct matching. Saved. Reloaded the Joxit/docker-registry-ui and boom worked again.

Hope this helps some other ones willing to use the Joxit thing and not willing to tune the registry server.

# Final words

Joxit, I take advantage of this post to congratulate you for your interface! Great work and thanks to for contributing to the world :D

**Comment by xmontero** [comment]
Cross-reference: http://forums.mozillazine.org/viewtopic.php?f=38&t=3061410&p=14863227#p14863227

**Comment by Joxit** [comment]
Hi @xmontero, thanks for your message, I happy to know that my work is appreciated :smile: 

I linked your comment in the [README](https://github.com/joxit/docker-registry-ui#using-cors)

**Comment by frakman1** [comment]
@xmontero @Joxit 

This firefox extension didn't work for me. See screenshot below:

![image](https://user-images.githubusercontent.com/5826484/100384673-aca2bb80-2fee-11eb-879c-1a5f780b2cb0.png)


I ran the default docker registry with:
` docker run -d -p 5000:5000  -e REGISTRY_STORAGE_DELETE_ENABLED=true  --restart=always --name registry registry:2`

I ran the UI like this:
 `docker run -d -p 80:80 -e URL=http://127.0.0.1:5000 -e DELETE_IMAGES=false joxit/docker-registry-ui:static`

I really don't want to have to re-configure how the registry is launched. I would like the UI piece to be de-coupled from the registry. The registry runs on a headless server so it doesn't have a UI so I can't launch a browser on it and open `http://127.0.0.1`

What are my options?

**Comment by Joxit** [comment]
Hi @frakman1 

You can try this example : https://github.com/Joxit/docker-registry-ui/blob/master/examples/ui-as-proxy/ (`simple.yml` for docker-compose)

Or add an option to your docker registry via the [config.yml](https://github.com/Joxit/docker-registry-ui/blob/master/examples/ui-as-standalone/registry-config/simple.yml)
```yml
http:
  headers:
    Access-Control-Allow-Origin: ['http://10.x.x.x']
```

**Comment by m3talstorm** [comment]
The value of `REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin` should be `['*']`

like:

`-e REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin="['*']"`

**Comment by khushwaqt** [comment]
I am facing this issue for CORS as well. Although i have tried most of the solutions but still not working. I am also fairly new to this docker thing so i am not sure what i am doing wrong here. Here are my configurations. 

########################################################
#                                        simple.yml                                                           #
########################################################

version: '2.0'
services:
  registry:
    image: registry:2.7
    ports:
      - 5050:5000
    volumes:
      - ./registry-data:/var/lib/registry
      - ./registry-config/simple.yml:/etc/docker/registry/config.yml

  ui:
    image: joxit/docker-registry-ui:latest
    ports:
      - 6379:80
    environment:
      - REGISTRY_TITLE=Staging Registry
      - REGISTRY_URL=http://172.21.182.103:5000
      - SINGLE_REGISTRY=true
    depends_on:
      - registry
	  
########################################################	  
#                 /registry-config/simple.yml                                                        #
########################################################
version: 0.1
log:
  fields:
    service: registry
storage:
  delete:
    enabled: true
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5050
  headers:
    X-Content-Type-Options: [nosniff]
    Access-Control-Allow-Origin: ['http://172.21.182.103:6379']
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
    Access-Control-Allow-Headers: ['Authorization', 'Accept']
    Access-Control-Max-Age: [1728000]
    Access-Control-Allow-Credentials: [true]
    Access-Control-Expose-Headers: ['Docker-Content-Digest']

###############################################################
#     /etc/docker-distribution/registry/config.yml                                                        #
###############################################################
version: 0.1
log:
  fields:
    service: registry
storage:
    cache:
        layerinfo: inmemory
    filesystem:
        rootdirectory: /var/lib/registry
http:
    addr: 172.21.182.103:5000
    headers:
      Access-Control-Allow-Origin: ['http://172.21.182.103:6379']
      Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
delete:
  enabled: true

after running `docker-compose -f simple.yml up -d` command and visiting browser i can see the page loading but after few seconds it says check your connection and registry must have 'Access-Control-Allow-Origin' header set to ""http://172.21.182.103:6379"

**Comment by Angel-Perez-Lopez** [comment]
I also have the problem that the CORS plugin was not helping me. 
This is what I did to help it.
1. Force the URL to use https://
2. The browser will tell you that this website is insecure. Go to Advance and select that you accept the risk. Nothing will be shown still on the website.
3. Go back in the URL and force again http:// (now the repositories and images will be shown.

This worked for me both in Microsoft Edge and Firefox
![image](https://user-images.githubusercontent.com/102669739/160834997-c2296add-c0e5-4169-bad0-c60b2aa0aa4b.png)

**Comment by emanuele-leopardi** [comment]
In case someone stumbled upon this issue and wants to have an equivalent addon for chromium-based browser you can use 
> https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf

I had a registry with no credentials, so the only change I had to do was to go to 
-> Open options page -> on `.5 Access Control Allow Origin` switch from `Origin` to `*`

**Comment by qn1213** [comment]
I added the Allow-Origin header, but the error still appears.

>An error occured: Check your connection and your registry must have `Access-Control-Allow-Origin` header set to `http://localhost:6001`

Chrome console log is
>GET http://locahost:5000/v2/_catalog?n=1000 net::ERR_NAME_NOT_RESOLVED

**Comment by Joxit** [comment]
Hi, please read the messages before sending issues...

Your chrome says 6000 is an unsafe port => change your port configuration and use the default one (5000) for example....
